Add more missing locale documentation
FakerPHP/fakerphp.github.io pull request #24
Opened 2020-12-04 18:00 UTC by krsriq

Adds missing documentation for a couple of locales.

2020-12-04 18:24 UTC, bramceulemans requested changes
Left you a comment, looks good to me otherwise!

2020-12-04 18:24 UTC, bramceulemans commented on docs/locales/en_IN.md
> +echo $faker->locality; // "Vaishali Nagar"
Can you add the rest of the methods here too? (`state`, etc.)

2020-12-04 19:12 UTC, krsriq commented on docs/locales/en_IN.md
> +echo $faker->locality; // "Vaishali Nagar"
`state` I left out here on purpose to keep it consistent - many `Address` providers have a `state` method, but only de_AT a documentation for that - I've added it now here.
Should I add the `state` to every `Address` doc (in a separate PR)?

2020-12-04 22:44 UTC, pimjansen commented on docs/locales/en_IN.md
> +echo $faker->locality; // "Vaishali Nagar"
bramceulemans aren't we documenting too much that way? Since state is part of the address core it's a bit overkill to document it on every locale.

Though it is not wrong and even could be useful since it gives a more representative output, it still feels a lot to maintain.

Views?

2020-12-04 22:45 UTC, bramceulemans commented on docs/locales/en_IN.md
> +echo $faker->locality; // "Vaishali Nagar"
I did not notice that state was in the core Address provider, if that's the case, ignore my comment.

2020-12-04 23:22 UTC, pimjansen commented on docs/locales/en_IN.md
> +echo $faker->locality; // "Vaishali Nagar"
Ah lol nvm it is not strange enough.

2020-12-05 07:53 UTC, krsriq commented on docs/locales/en_IN.md
> +echo $faker->locality; // "Vaishali Nagar"
> Ah lol nvm it is not strange enough.

Yes - so we could either leave it in the docs here as is done in this PR (and add it to the other `Address` documentation for consistency), or add a `state` method to the core? 
I counted 23 (of 47) localized Address providers that have a state method. There are probably more that have a method that's comparable to `state`, but differently named.

2020-12-07 22:07 UTC, pimjansen approved these changes

2020-12-07 22:07 UTC, merged