Doc RUC
FakerPHP/fakerphp.github.io pull request #33
Opened 2021-01-04 04:36 UTC by Oxicode

Doc https://github.com/FakerPHP/Faker/pull/244

2021-01-04 07:16 UTC, pimjansen requested changes

2021-01-04 07:16 UTC, pimjansen commented on docs/locales/es_PE.md
> +echo $faker->ruc; // '20105895410'
Code indicates a 10x number

2021-01-04 07:16 UTC, pimjansen commented on docs/locales/es_PE.md
> +echo $faker->ruc(true); // '20105895410'
Same here if im correct

2021-01-05 04:45 UTC, Oxicode commented on docs/locales/es_PE.md
> +echo $faker->ruc(true); // '20105895410'
done

2021-01-05 06:32 UTC, pimjansen approved these changes

2021-01-05 06:32 UTC, pimjansen commented
Thanks

2021-01-05 08:29 UTC, merged