Remove more mentions of property access
FakerPHP/fakerphp.github.io pull request #36
Opened 2021-01-10 18:41 UTC by krsriq

There were a couple more mentions of direct property access that are replaced with method calls in this PR.

2021-01-10 20:36 UTC, bramceulemans commented on docs/index.md
> +    echo $faker->name(), "\n";
```suggestion
    echo $faker->name() . "\n";
```

2021-01-10 20:37 UTC, bramceulemans commented on docs/index.md
> -// generate data by accessing properties
Why'd you remove this?

2021-01-10 22:35 UTC, GrahamCampbell requested changes

2021-01-10 22:35 UTC, GrahamCampbell commented on docs/locales/pt_BR.md
> +echo $faker->cnpj();        // '23.663.478/0001-24'
two too many space characters now

2021-01-10 22:35 UTC, GrahamCampbell commented on docs/index.md
> -// generate data by accessing properties
I think this comment just needs replacing, rather than being removed

2021-01-11 07:53 UTC, krsriq commented on docs/index.md
> -// generate data by accessing properties
I re-added this now but changed the comment.

2021-01-11 07:53 UTC, krsriq commented on docs/locales/pt_BR.md
> +echo $faker->cnpj();        // '23.663.478/0001-24'
Thanks, fixed!

2021-01-11 08:51 UTC, bramceulemans approved these changes
Looks good to me now!

2021-01-11 15:51 UTC, merged